In [1]:
import numpy as np

In [2]:
X_trn=np.array([[24000,8],
                [30000,2],
                [35000,7],
                [34500,1]])
X_test=np.array([[34000,7],[12000,1]])

In [3]:
### Standard Scaling
col1=X_trn[:,0]
trf_col1=(col1-np.mean(col1))/np.std(col1)
print(np.mean(trf_col1),np.std(trf_col1))
print("Transform col1: \n",trf_col1)
col2=X_trn[:,1]
trf_col2=(col2-np.mean(col2))/np.std(col2)
print(np.mean(trf_col2),np.std(trf_col2))
print("Transform col2: \n",trf_col2)

0.0 1.0
Transform col1: 
 [-1.55501304 -0.19791075  0.93300782  0.81991597]
0.0 1.0
Transform col2: 
 [ 1.15079291 -0.82199494  0.82199494 -1.15079291]


In [4]:
### All columns at once
means=X_trn.mean(axis=0)
stds=X_trn.std(axis=0)
print((X_trn-means)/stds)
print("means",means)
print("STD",stds)

[[-1.55501304  1.15079291]
 [-0.19791075 -0.82199494]
 [ 0.93300782  0.82199494]
 [ 0.81991597 -1.15079291]]
means [3.0875e+04 4.5000e+00]
STD [4.42118480e+03 3.04138127e+00]


In [5]:
print((X_test-means)/stds) # To scale X_test use (mean,std) of X_train

[[ 0.70682411  0.82199494]
 [-4.26921761 -1.15079291]]


In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
print(scaler.fit_transform(X_trn))

[[-1.55501304  1.15079291]
 [-0.19791075 -0.82199494]
 [ 0.93300782  0.82199494]
 [ 0.81991597 -1.15079291]]


In [7]:
print("means ",scaler.mean_)
print("Standard Deviation ",scaler.scale_)

means  [3.0875e+04 4.5000e+00]
Standard Deviation  [4.42118480e+03 3.04138127e+00]


### with image segmentation

In [8]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import log_loss,accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [9]:
image=pd.read_csv("Image_Segmention.csv")
image.head()

Class  region.centroid.col  region.centroid.row  region.pixel.count  \
0  BRICKFACE                  188                  133                   9   
1  BRICKFACE                  105                  139                   9   
2  BRICKFACE                   34                  137                   9   
3  BRICKFACE                   39                  111                   9   
4  BRICKFACE                   16                  128                   9   

   short.line.density.5  short.line.density.2  vedge.mean  vegde.sd  \
0                   0.0                   0.0    0.333333  0.266667   
1                   0.0                   0.0    0.277778  0.107407   
2                   0.0                   0.0    0.500000  0.166667   
3                   0.0                   0.0    0.722222  0.374074   
4                   0.0                   0.0    0.500000  0.077778   

   hedge.mean  hedge.sd  intensity.mean  rawred.mean  rawblue.mean  \
0    0.500000  0.077778        6.666666     8.333334      7.777778   
1    0.833333  0.522222        6.111111     7.555555      7.222222   
2    1.111111  0.474074        5.851852     7.777778      6.444445   
3    0.888889  0.429629        6.037037     7.000000      7.666666   
4    0.666667  0.311111        5.555555     6.888889      6.666666   

   rawgreen.mean  exred.mean  exblue.mean  exgreen.mean  value.mean  \
0       3.888889    5.000000     3.333333     -8.333333    8.444445   
1       3.555556    4.333334     3.333333     -7.666666    7.555555   
2       3.333333    5.777778     1.777778     -7.555555    7.777778   
3       3.444444    2.888889     4.888889     -7.777778    7.888889   
4       3.111111    4.000000     3.333333     -7.333334    7.111111   

   saturation.mean  hue-mean  
0         0.538580 -0.924817  
1         0.532628 -0.965946  
2         0.573633 -0.744272  
3         0.562919 -1.175773  
4         0.561508 -0.985811

In [10]:
lbl=LabelEncoder()
image['Class']=lbl.fit_transform(image['Class'])
X = image.drop("Class",axis =1)
y = image['Class']

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=23,stratify=y)

### Without Scaling the X_train and X_test

In [12]:
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
print(accuracy_score(y_test,y_pred))


0.8095238095238095


In [13]:
y_pred_proba=knn.predict_proba(X_test)
log_loss(y_test,y_pred_proba)

6.86545778840327

### After Scaling the X_train and X_test

In [14]:
scaler  = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [15]:
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
print(accuracy_score(y_test,y_pred))


0.8253968253968254


In [17]:
y_pred_proba=knn.predict_proba(X_test)
log_loss(y_test,y_pred_proba)

6.29333630603633