In [2]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer

In [6]:
X = np.array([[1,2,np.nan],
             [8,6.3,5],
             [np.nan,3.5,6.7],
             [1.25,4.2,1],
             [1.2,2.4,3],
             [np.nan,6,5],
             [10,6.43,5.61]])

In [7]:
imputer = KNNImputer(n_neighbors=1)
imputer.fit_transform(X)

array([[ 1.  ,  2.  ,  3.  ],
       [ 8.  ,  6.3 ,  5.  ],
       [ 1.  ,  3.5 ,  6.7 ],
       [ 1.25,  4.2 ,  1.  ],
       [ 1.2 ,  2.4 ,  3.  ],
       [ 8.  ,  6.  ,  5.  ],
       [10.  ,  6.43,  5.61]])

In [8]:
imputer = KNNImputer(n_neighbors=2)
imputer.fit_transform(X)

array([[ 1.  ,  2.  ,  4.85],
       [ 8.  ,  6.3 ,  5.  ],
       [ 5.5 ,  3.5 ,  6.7 ],
       [ 1.25,  4.2 ,  1.  ],
       [ 1.2 ,  2.4 ,  3.  ],
       [ 9.  ,  6.  ,  5.  ],
       [10.  ,  6.43,  5.61]])

In [9]:
imputer = KNNImputer(n_neighbors=3)
imputer.fit_transform(X)

array([[ 1.        ,  2.        ,  3.56666667],
       [ 8.        ,  6.3       ,  5.        ],
       [ 6.33333333,  3.5       ,  6.7       ],
       [ 1.25      ,  4.2       ,  1.        ],
       [ 1.2       ,  2.4       ,  3.        ],
       [ 6.4       ,  6.        ,  5.        ],
       [10.        ,  6.43      ,  5.61      ]])